### ISSUE TITLE
Issues when images are rendered more than once

### ISSUE THREAD

**Issue by supraditya** [mattConn/csc430-webapp#1]
So I was referred to your code to essentially understand how you rendered a networkx graph object within a Flask application, and on cloning your repository, I realised that rendering the image more than once led to a huge chain of runtime errors. Upon investigation I found the following article, and I think it should help your project as well!

https://stackoverflow.com/questions/27147300/matplotlib-tcl-asyncdelete-async-handler-deleted-by-the-wrong-thread/29172195#29172195

Hope this helps!

-supraditya

**Comment by mattConn** [comment]
Thanks for this! It has been a while since I've looked at this repo (almost a year?), I'm glad it's of use to other developers. I'll try to reproduce this bug, and if it's just a matter of changing matplotlib's backend, that's a quick enough fix.

**Comment by supraditya** [comment]
Anytime! Happy to help, and I wanted to thank you for your implementation of the matplotlib rendering, it helped me a lot! (and even a friend of mine who was coincidentally stuck on the same problem!)
